spring:
  application:
    name: config-server
server:
  port: 8888
  cloud:
    config:
      server:
        git:
          uri: https://github.com/franklinconde1/service-configuration.git
          default-label: main
          clone-on-start: true